### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by TheMisfit68** [LarsJK/libmodbus-swift#1]
When adding this package as a dependency to an Xcode 11 beta project you get "Package Resolution Failed"

**Comment by LarsJK** [comment]
Sorry for the late reply.. I dont really maintain this. Should add a README.. Do you have the "
/usr/local/include/modbus/modbus.h" file on your system? Do you have homebrew installed?

Could you try to only import clibmodbus? Then add the swift files from this project manually..?

**Comment by TheMisfit68** [comment]
Lars,
Both are installed. I don't think there is a problem with the project itself rather with the Package-manifest not using the latest swift-tools-version:5.1. syntax.
Been playing with this and it might be because clibmodbus is used as a separate wrapper package not as as system library target, with I understand is the preferred way to include a C-based system library this days.
From the SPM doc:
As of Swift 4.2, the package manager is capable of importing C libraries from the system without requiring a special wrapper package.

but I'm a total newbie, so I might be wrong.

**Comment by LarsJK** [comment]
I think you are right. Both the package manifests and the source code use old swift syntax and that seems to be the issue..
I don't think the separate wrapper (Clibmodbus) is an issue, its only deprecated and not removed, but I tried to quickly update the syntax and removing the wrapper..
Could you try this one out? https://github.com/LarsJK/Modbus-swift

I don't plan on maintaining the package tho. I don't work with modbus anymore.

**Comment by TheMisfit68** [comment]
works like a charm now :-) thnx for getting me started
